### ISSUE TITLE
Recoll version is out of date

### ISSUE THREAD

**Issue by mgmeyers** [nailuoGG/homebrew-recoll#2]
This formula points to 1.30.1 and the latest version is 1.32.0

**Comment by nailuoGG** [comment]
Hello,

Good news! The package is now updated to the latest version, 1.37.4, directly from Recoll's [official website](https://www.lesbonscomptes.com/recoll/pages/recoll-macos.html). Feel free to install it and let us know if you need any assistance.

Best wishes.
